@Library('shared-libarary@master') _

pipeline {
    agent any

    
    stages {
        stage('Chekout')
        {
            steps {
                // Perform the Git checkout
                git url: 'https://github.com/argadepp/Spring-boot-docker-img.git'
            }
        }
        // stage('Build') {
        //     steps {
        //         script {
        //             buildApp('MyApp')
        //         }
        //     }
        // }

        stage('Build Docker') {
            steps {
                script {
                    buildDocker('ghcr.io/argadepp/javaapp','v1','.')
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    deployApp('MyApp', 'staging')
                }
            }
        }
        stage('Notify') {
            steps {
                script {
                    notifySlack('Deployment completed for MyApp', '#devops')
                }
            }
        }
    }
}
