@Library('shared-libarary@master') _

pipeline {
    agent any

    
    stages {
        stage('Chekout')
        {
            git 'https://github.com/argadepp/Spring-boot-docker-img.git'
        }
        stage('Build') {
            steps {
                script {
                    buildApp('MyApp')
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    deployApp('MyApp', 'staging')
                }
            }
        }
        stage('Notify') {
            steps {
                script {
                    notifySlack('Deployment completed for MyApp', '#devops')
                }
            }
        }
    }
}
