allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2encrypt
parameters:
  fsType: ext4
  type: gp2
  encrypted: "true"
  kmsKeyId: ""
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
